name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Push to another repository
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          cd ${{ github.workspace }}
          mkdir download
          cd download
          git clone -b master https://github.com/mingriyingying/zjc_notes.git
          cd zjc_notes/
          git init
          git add .
          git commit -m "Add GitHub Actions workflow"
          git remote add origin https://github.com/mingriyingying/mingriyingying.github.io.git
          git push origin doc





