name: Deploy to GitHub Pages
on:
  push: 
    branches: 
      - master
jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: git@github.com:mingriyingying/mingriyingying.github.io.git
        BRANCH: doc
        FOLDER: aritcles
        SSH_PRIVATE_KEY: ${{ secrets.sinovatio-thinkpad-x270 }}
