name: Trigger Update Event

on:
  push:
    branches:
      - master

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Repository B Workflow
        run: |
          curl -X POST https://api.github.com/repos/mingriyingying/mingriyingying.github.io/dispatches \
          -H "Authorization: token ${{ secrets.UPDATE_EVENT }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -d '{"event_type": "update-event"}'